### ISSUE TITLE
在启用了 native-compile 的 Emacs 上报错，原因是 benchmark-init 这个包。

### ISSUE THREAD

**Issue by ixnij** [cabins/.emacs.d#1]
使用这份配置文件，会在启用了 Native-compile 的 Emacs 28 上报错。我的配置文件也会爆出同样的错误： Wrong arguments: (3 . 4) 2 。使用 `emacs --debug-init` 排查后，追根溯源发现是 `benchmark-init` 这个包的问题，只要把这个包移除就好。

朋友的这份配置文件也是一样，在 lisp/init-package.el 里边，把 benchmark-init 这个移除就可以用了。这个包太老，好久没更新了，melpa 这里显示上一次更新是 2015 年，是时候寻找替代品了。

**Comment by cabins** [comment]
> 使用这份配置文件，会在启用了 Native-compile 的 Emacs 28 上报错。我的配置文件也会爆出同样的错误： Wrong arguments: (3 . 4) 2 。使用 `emacs --debug-init` 排查后，追根溯源发现是 `benchmark-init` 这个包的问题，只要把这个包移除就好。
> 
> 朋友的这份配置文件也是一样，在 lisp/init-package.el 里边，把 benchmark-init 这个移除就可以用了。这个包太老，好久没更新了，melpa 这里显示上一次更新是 2015 年，是时候寻找替代品了。

经验证确实如此，应该要去掉这个包。非常感谢！！

**Comment by ixnij** [comment]
> > 使用这份配置文件，会在启用了 Native-compile 的 Emacs 28 上报错。我的配置文件也会爆出同样的错误： Wrong arguments: (3 . 4) 2 。使用 `emacs --debug-init` 排查后，追根溯源发现是 `benchmark-init` 这个包的问题，只要把这个包移除就好。
> > 朋友的这份配置文件也是一样，在 lisp/init-package.el 里边，把 benchmark-init 这个移除就可以用了。这个包太老，好久没更新了，melpa 这里显示上一次更新是 2015 年，是时候寻找替代品了。
> 
> 经验证确实如此，应该要去掉这个包。非常感谢！！

好的，没事！
