### ISSUE TITLE
为何git 配置跟简书 Emacs高手修炼手册 上说明不太一样

### ISSUE THREAD

**Issue by Jack126** [cabins/.emacs.d#2]
hello，cabins：
     如题

**Comment by cabins** [comment]
我现在的git配置已经追求轻量和简洁了。所以第三方的软件包已经基本删除。

跟着我高手修炼手册去练习的话，可以
1）要么Check一个我当初的commit
2）要么自己去对照着写一套配置

建议第二个吧。那样会掌握的多一些。

**Comment by cabins** [comment]
我感觉后面你一定也会慢慢的去使用简洁的配置的。因为，体验确实不错。

**Comment by cabins** [comment]
https://github.com/cabins/.emacs.d/releases/tag/v0.0.1

我把当初的代码打了tag创建了一个release。你可以参考。

**Comment by Jack126** [comment]
> 我现在的git配置已经追求轻量和简洁了。所以第三方的软件包已经基本删除。
> 
> 跟着我高手修炼手册去练习的话，可以 1）要么Check一个我当初的commit 2）要么自己去对照着写一套配置
> 
> 建议第二个吧。那样会掌握的多一些。

感谢，用了很多人的，发现你这个最简洁，最流畅
