### ISSUE TITLE
use-package报错

### ISSUE THREAD

**Issue by CMingXiang** [cabins/.emacs.d#5]
你好
系统是win10专业版，在clone你的配置之后，看到init-ide文件中下面代码：
-------------------------------------------------------------------------------------------------------
(use-package eglot
  :hook ((c-mode c++-mode go-mode java-mode js-mode python-mode rust-mode web-mode) . eglot-ensure)
  :bind (("C-c e f" . #'eglot-format)
         ("C-c e i" . #'eglot-code-action-organize-imports)
         ("C-c e q" . #'eglot-code-action-quickfix))
------------------------------------------------------------------------------------------------------
在hook (...).eglot-ensure提示警告，提示”(c-mode c++-mode go-mode java-mode js-mode python-mode rust-mode web-mode)"is a malformed function,
’("C-c e f" . #'eglot-format)‘ is a malformed function。
然后同样这个文件最下面：“(use-package restclient
  :mode (("\\.http\\'" . restclient-mode)))”这里同样警告说’("\\.http\\'" . restclient-mode‘ is a malformed function。

所以想请教你该怎么解决？拜托，谢谢

**Comment by CMingXiang** [comment]
![init el](https://user-images.githubusercontent.com/39574567/150637779-c044c86c-cf28-454a-92e2-e5ba7e76a494.png)

**Comment by cabins** [comment]
那个是flymake的语法检查，不影响正常的逻辑和代码运行。如果实在是代码“洁癖”（没有恶意哈，一时想不出来更合适的词语），可以将所有的malformed function添加到init中，然后改写成原生的elisp代码，比如，:hook改写成(add-hook 'c-mode-hook #'eglot-ensure)这样的格式。

**Comment by cabins** [comment]
其实我也一直纳闷为啥flymake的语法检查对use-package的宏这么严格。但后来我放弃了改写（曾经有一段时间我也在为次苦恼），因为use-package使用的keyword实在是太好用了。

**Comment by CMingXiang** [comment]
谢谢您的回复，我主要是担心会影响到emacs的运行，如果只是语法审查的问题的话，那我就没有什么问题了。
再次感谢！



***@***.***
 
发件人： Cabins
发送时间： 2022-01-24 09:46
收件人： cabins/.emacs.d
抄送： C_KL; State change
主题： Re: [cabins/.emacs.d] use-package报错 (Issue #5)
其实我也一直纳闷为啥flymake的语法检查对use-package的宏这么严格。但后来我放弃了改写（曾经有一段时间我也在为次苦恼），因为use-package使用的keyword实在是太好用了。
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
